---
resources:
- name: spring-hello-version
  type: semver
  source:
    driver: s3
    bucket: {{concourse-bucket}}
    key: semvar
    access_key_id: {{s3-access-token}}
    secret_access_key: {{s3-secret-key}}
    region_name: us-east-1
    initial_version: 1.0.0

- name: spring-hello-war
  type: s3
  source:
    bucket: {{concourse-bucket}}
    regexp: gs-spring-boot-(.*).jar
    access_key_id: {{s3-access-token}}
    secret_access_key: {{s3-secret-key}}

- name: spring-hello-repo
  type: git
  source: 
    uri: https://github.com/pvtl-shane/gs-spring-boot
    branch: master
    
- name: cf-dev
  type: cf
  source:
    api: {{cf-target}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-dev-organization}}
    space: {{cf-dev-space}}
#
#- name: cf-staging
#  type: cf
#  source:
#    api: {{cf-target}}
#    username:
#    password:
#    organization:
#    space:
#
#- name: cf-perf
#  type: cf
#  source:
#    api:
#    username:
#    password:
#    organization:
#    space:

jobs:
- name: build
  plan:
  - get: spring-hello-repo
    trigger: true
  - get: spring-hello-version
    params: {bump: minor}
  - task: build
    file: spring-hello-repo/complete/ci/tasks/build.yml
  - put: spring-hello-war
    params: {file: art/gs-spring-boot-*.jar}
  - put: spring-hello-version
    params: {file: spring-hello-version/number}

- name: deploy-to-dev
  plan:
    - get: spring-hello-repo
      passed: [build]
    - get: spring-hello-war
      passed: [build]
      trigger: true
    - put: cf-dev
      params:
        manifest: spring-hello-repo/complete/manifests/dev-manifest.yml
        path: spring-hello-war/gs-spring-boot-*.jar
    - task: run-functional-tests
      file: spring-hello-repo/complete/ci/tasks/functional-tests.yml