#!/usr/bin/env bash

VERSION=`cat spring-hello-version/number`
STARTING_DIRECTORY=`pwd`

cd spring-hello-repo/complete
./gradlew clean test build -Pwar_version="$VERSION"
ls -al build/libs/

mkdir "STARTING_DIRECTORY/art"
mv "build/libs/gs-spring-boot-$VERSION.jar" "STARTING_DIRECTORY/art/"