#!/usr/bin/env bash

VERSION=`cat spring-hello-version/number`
HUH=`pwd`

echo "$HUH"
echo "$VERSION"

cd spring-hello-repo/complete
./gradlew clean test build -Pwar_version="$VERSION"
ls -al build/libs/

echo "Moving to $HUH/art"
mkdir "$HUH/art"
mv "build/libs/gs-spring-boot-$VERSION.jar" "$HUH/art/"
ls "$HUH/art/"